baseurl = "https://jrivero.net"
title = "Jordi Rivero"

theme = "coder"

languagecode = "es"

paginate = 30
canonifyurls = false

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = ""

[params]
    author = "Jordi Rivero"
    info = "Director Técnico, Desarrollador, Fotógrafo desde Barcelona"

    description = "Director Técnico, Desarrollador, Fotógrafo desde Barcelona"
    keywords = "blog,developer,personal,cto,software,engineer,barcelona"

    hideCredits = true
    hideCopyright = true

    # Custom CSS
  	custom_css = []

[[params.social]]
    name = "Twitter"
    weight = 1
    url = "https://twitter.com/jrivero/"
[[params.social]]
    name = "LinkedIn"
    weight = 2
    url = "https://www.linkedin.com/in/jordirivero/"
[[params.social]]
    name = "Github"
    weight = 3
    url = "https://github.com/jrivero/"

[[menu.main]]
    name = "Conóceme"
    weight = 2
    url = "/jordi-rivero/"
