baseurl = "http://battlelands-royale.com/"
title = "Battlelands Royale"

theme = "coder"

languagecode = "es"

paginate = 30
canonifyurls = false

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = ""

[params]
    author = "Battlelands Royale"
    info = "Battle Royale. On Mobile. Done Right."

    description = "Battlelands Royale. Battle Royale. On Mobile. Done Right. Battlelands Royale has landed. Download free on iOS and Android below. #LootShootSurvive"
    keywords = "battlelands,royale,fortnite,juego"

    hideCredits = true
    hideCopyright = true

    # Custom CSS
  	custom_css = []

[[params.social]]
    name = "Instagram"
    weight = 1
    url = "https://www.instagram.com/battlelandsroyale/"

[[menu.main]]
    name = "Descargar"
    weight = 2
    url = "/descargar/"
