baseurl = "https://jrivero.net"
title = "Jordi Rivero"

theme = "coder"

languagecode = "es"

paginate = 30
canonifyurls = false

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "jrivero"

[params]
    author = "Jordi Rivero"
    description = "Director Técnico, Desarrollador, Fotógrafo desde Barcelona"
    keywords = "blog,developer,personal,cto,barcelona"
    info = "Director Técnico, Desarrollador, Fotógrafo desde Barcelona"

    hideCredits = true
    hideCopyright = true

    # Custom CSS
	custom_css = []

[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/jrivero/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/jrivero/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/jordirivero/"

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "Conóceme"
    weight = 2
    url = "/acerca-de/"
